language: php
php:
  - 5.5
  - 5.6
  - 7.0
before_install:
  - composer self-update
install:
  - travis_retry composer install --no-interaction --prefer-source
before_script:
  - phpenv config-rm xdebug.ini